"""update_user_relationships_cascade_rules

Revision ID: 074576b32cc4
Revises: f5e59ac8cf02
Create Date: 2025-05-05 23:43:27.072270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074576b32cc4'
down_revision: Union[str, None] = 'f5e59ac8cf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_uploaded_by_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_folder_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['uploaded_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folders_parent_folder_id_fkey', 'folders', type_='foreignkey')
    op.drop_constraint('folders_owner_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shared_items_shared_by_fkey', 'shared_items', type_='foreignkey')
    op.drop_constraint('shared_items_shared_with_fkey', 'shared_items', type_='foreignkey')
    op.create_foreign_key(None, 'shared_items', 'users', ['shared_with'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shared_items', 'users', ['shared_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_file_permissions_user_id_fkey', 'user_file_permissions', type_='foreignkey')
    op.drop_constraint('user_file_permissions_file_id_fkey', 'user_file_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_file_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_file_permissions', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_folder_permissions_user_id_fkey', 'user_folder_permissions', type_='foreignkey')
    op.drop_constraint('user_folder_permissions_folder_id_fkey', 'user_folder_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_folder_permissions', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_folder_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folder_permissions', type_='foreignkey')
    op.drop_constraint(None, 'user_folder_permissions', type_='foreignkey')
    op.create_foreign_key('user_folder_permissions_folder_id_fkey', 'user_folder_permissions', 'folders', ['folder_id'], ['id'])
    op.create_foreign_key('user_folder_permissions_user_id_fkey', 'user_folder_permissions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_file_permissions', type_='foreignkey')
    op.drop_constraint(None, 'user_file_permissions', type_='foreignkey')
    op.create_foreign_key('user_file_permissions_file_id_fkey', 'user_file_permissions', 'files', ['file_id'], ['id'])
    op.create_foreign_key('user_file_permissions_user_id_fkey', 'user_file_permissions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'shared_items', type_='foreignkey')
    op.drop_constraint(None, 'shared_items', type_='foreignkey')
    op.create_foreign_key('shared_items_shared_with_fkey', 'shared_items', 'users', ['shared_with'], ['id'])
    op.create_foreign_key('shared_items_shared_by_fkey', 'shared_items', 'users', ['shared_by'], ['id'])
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_owner_id_fkey', 'folders', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('folders_parent_folder_id_fkey', 'folders', 'folders', ['parent_folder_id'], ['id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_folder_id_fkey', 'files', 'folders', ['folder_id'], ['id'])
    op.create_foreign_key('files_uploaded_by_id_fkey', 'files', 'users', ['uploaded_by_id'], ['id'])
    # ### end Alembic commands ###
