"""Added filepermission folder model

Revision ID: e7f33ea6b785
Revises: faa34a26f187
Create Date: 2025-02-15 20:58:10.390416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f33ea6b785'
down_revision: Union[str, None] = 'faa34a26f187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_items', 'item_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='item_id::text::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_items', 'item_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='item_id::text::integer')
    # ### end Alembic commands ###
